### ISSUE TITLE
Please re-name the project to avoid IP infringement

### ISSUE THREAD

**Issue by Cyriuz** [lettucegoblin/pureref-gif-support#11]
Hi! Just a friendly heads up that you can't use the PureRef name, even as part of your own product names. Having your own unique name will also prevent any possible confusion and ensure that your project receives the unique identity it deserves.

Thanks!

**Comment by lettucegoblin** [comment]
That's a good idea, didn't think of that. I'll do that over the next few days. Maybe AnimRef.

**Comment by lettucegoblin** [comment]
https://github.com/lettucegoblin/AnimRef/releases/tag/v1.0.4-alpha
New release! If you have any other suggestions keep'em coming!
