### ISSUE TITLE
License specification

### ISSUE THREAD

**Issue by hadrien-toma** [lettucegoblin/pureref-gif-support#5]
Hello @lettucegoblin :wave:,

First, I need to thank you for this awesome project, perfectly doing its job. I created this issue to ask you if you would agree to add a LICENSE file at the root of the repository in order to explain users the conditions of the project? I would be so happy to see this project with a very open and sharable LICENSE file (maybe BSC, MIT or Apache-2.0?).

Again, thank you very much for the work and share!

**Comment by lettucegoblin** [comment]
Sure, ill do that now! Good idea!

**Comment by lettucegoblin** [comment]
Done! Thank you for the suggestion!
